//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.12 at 03:35:18 PM PST 
//


package com.kp.fof.productzero.core.fflxmlhelper;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for facilityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="facilityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="official_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="facility_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="core" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cpm_facilities" type="{}cpm_facilitiesType"/>
 *         &lt;element name="affiliated_facility" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="servicearea_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="address" type="{}addressType"/>
 *         &lt;element name="phone_numbers" type="{}phone_numbersType"/>
 *         &lt;element name="related_zipcodes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="search_keywords" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="facilityId" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "facilityType", propOrder = {
    "officialName",
    "url",
    "facilityType",
    "core",
    "cpmFacilities",
    "affiliatedFacility",
    "serviceareaName",
    "address",
    "phoneNumbers",
    "relatedZipcodes",
    "searchKeywords"
})
public class FacilityType {

    @XmlElement(name = "official_name", required = true)
    protected String officialName;
    @XmlElement(required = true)
    protected String url;
    @XmlElement(name = "facility_type", required = true)
    protected String facilityType;
    @XmlElement(required = true)
    protected String core;
    @XmlElement(name = "cpm_facilities", required = true)
    protected CpmFacilitiesType cpmFacilities;
    @XmlElement(name = "affiliated_facility", required = true)
    protected String affiliatedFacility;
    @XmlElement(name = "servicearea_name", required = true)
    protected String serviceareaName;
    @XmlElement(required = true)
    protected AddressType address;
    @XmlElement(name="phone_numbers",required = true)
    protected PhoneNumbersType phoneNumbers;
    @XmlElement(name = "related_zipcodes", required = true)
    protected String relatedZipcodes;
    @XmlElement(name = "search_keywords", required = true)
    protected String searchKeywords;
    @XmlAttribute(name = "facilityId")
    protected Integer facilityId;
    @XmlAttribute(name = "href")
    protected String href;

    /**
     * Gets the value of the officialName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfficialName() {
        return officialName;
    }

    /**
     * Sets the value of the officialName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfficialName(String value) {
        this.officialName = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the facilityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacilityType() {
        return facilityType;
    }

    /**
     * Sets the value of the facilityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacilityType(String value) {
        this.facilityType = value;
    }

    /**
     * Gets the value of the core property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCore() {
        return core;
    }

    /**
     * Sets the value of the core property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCore(String value) {
        this.core = value;
    }

    /**
     * Gets the value of the cpmFacilities property.
     * 
     * @return
     *     possible object is
     *     {@link CpmFacilitiesType }
     *     
     */
    public CpmFacilitiesType getCpmFacilities() {
        return cpmFacilities;
    }

    /**
     * Sets the value of the cpmFacilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link CpmFacilitiesType }
     *     
     */
    public void setCpmFacilities(CpmFacilitiesType value) {
        this.cpmFacilities = value;
    }

    /**
     * Gets the value of the affiliatedFacility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffiliatedFacility() {
        return affiliatedFacility;
    }

    /**
     * Sets the value of the affiliatedFacility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffiliatedFacility(String value) {
        this.affiliatedFacility = value;
    }

    /**
     * Gets the value of the serviceareaName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceareaName() {
        return serviceareaName;
    }

    /**
     * Sets the value of the serviceareaName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceareaName(String value) {
        this.serviceareaName = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setAddress(AddressType value) {
        this.address = value;
    }

    /**
     * Gets the value of the phoneNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link PhoneNumbersType }
     *     
     */
    public PhoneNumbersType getPhoneNumbers() {
        return phoneNumbers;
    }

    /**
     * Sets the value of the phoneNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhoneNumbersType }
     *     
     */
    public void setPhoneNumbers(PhoneNumbersType value) {
        this.phoneNumbers = value;
    }

    /**
     * Gets the value of the relatedZipcodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedZipcodes() {
        return relatedZipcodes;
    }

    /**
     * Sets the value of the relatedZipcodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedZipcodes(String value) {
        this.relatedZipcodes = value;
    }

    /**
     * Gets the value of the searchKeywords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchKeywords() {
        return searchKeywords;
    }

    /**
     * Sets the value of the searchKeywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchKeywords(String value) {
        this.searchKeywords = value;
    }

    /**
     * Gets the value of the facilityId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFacilityId() {
        return facilityId;
    }

    /**
     * Sets the value of the facilityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFacilityId(Integer value) {
        this.facilityId = value;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHref(String value) {
        this.href = value;
    }

}
