//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.12 at 03:35:18 PM PST 
//


package com.kp.fof.productzero.core.fflxmlhelper;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for phoneType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="phoneType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="phone_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phone_number" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="vanity_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phoneTags" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="formattedPhNbr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="kp_hours" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "phoneType", propOrder = {
    "phoneType",
    "phoneNumber",
    "vanityNumber",
    "description",
    "label",
    "phoneTags",
    "formattedPhNbr"
})
public class PhoneType {

    @XmlElement(name = "phone_type", required = true)
    protected String phoneType;
    @XmlElement(name = "phone_number", required = true)
    protected BigDecimal phoneNumber;
    @XmlElement(name = "vanity_number", required = true)
    protected String vanityNumber;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String label;
    @XmlElement(required = true)
    protected String phoneTags;
    @XmlElement(required = true)
    protected String formattedPhNbr;
    @XmlAttribute(name = "kp_hours")
    protected String kpHours;

    /**
     * Gets the value of the phoneType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneType() {
        return phoneType;
    }

    /**
     * Sets the value of the phoneType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneType(String value) {
        this.phoneType = value;
    }

    /**
     * Gets the value of the phoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPhoneNumber(BigDecimal value) {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the vanityNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVanityNumber() {
        return vanityNumber;
    }

    /**
     * Sets the value of the vanityNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVanityNumber(String value) {
        this.vanityNumber = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the phoneTags property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneTags() {
        return phoneTags;
    }

    /**
     * Sets the value of the phoneTags property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneTags(String value) {
        this.phoneTags = value;
    }

    /**
     * Gets the value of the formattedPhNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormattedPhNbr() {
        return formattedPhNbr;
    }

    /**
     * Sets the value of the formattedPhNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormattedPhNbr(String value) {
        this.formattedPhNbr = value;
    }

    /**
     * Gets the value of the kpHours property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKpHours() {
        return kpHours;
    }

    /**
     * Sets the value of the kpHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKpHours(String value) {
        this.kpHours = value;
    }

}
